name: Create modpack

on:
  push:
    tags:
      - '*'

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Zip modpack
        run: zip -r "create-19th_${{ github.ref_name }}.mrpack" modrinth.index.json overrides

      - uses: actions/upload-artifact@v6
        with:
          name: create-19th_${{ github.ref_name }}.mrpack
          path: create-19th_${{ github.ref_name }}.mrpack
          if-no-files-found: 'error'