name: Create modpack

on:
  push:
    tags:
      - '*'

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Copy default config
        run: |
          cp -r overrides/configureddefaults/config overrides/config
          cp -r overrides/configureddefaults/config overrides/defaultconfigs

      - name: Zip modpack
        run: zip -r "create-19th_${{ github.ref_name }}.mrpack" modrinth.index.json overrides

      - uses: actions/upload-artifact@v6
        with:
          name: create-19th_${{ github.ref_name }}.mrpack
          path: create-19th_${{ github.ref_name }}.mrpack
          if-no-files-found: 'error'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body: "to fill in"
          files: create-19th_${{ github.ref_name }}.mrpack
          fail_on_unmatched_files: true